config/routes.rb
Maildemo::Application.routes.draw do
  resources :scmails

end

app/models/scmail.rb
class Scmail < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/scmails_controller.rb
class ScmailsController < ApplicationController
  # GET /scmails
  # GET /scmails.xml
  def index
    @scmails = Scmail.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @scmails }
    end
  end

  # GET /scmails/1
  # GET /scmails/1.xml
  def show
    @scmail = Scmail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @scmail }
    end
  end

  # GET /scmails/new
  # GET /scmails/new.xml
  def new
    @scmail = Scmail.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @scmail }
    end
  end

  # GET /scmails/1/edit
  def edit
    @scmail = Scmail.find(params[:id])
  end

  # POST /scmails
  # POST /scmails.xml
  def create
    @scmail = Scmail.new(params[:scmail])

    respond_to do |format|
      if @scmail.save
        ScmailMailer.scheduled_email(@scmail).deliver
        format.html { redirect_to(@scmail, :notice => 'Your mail was successfully scheduled.') }
        format.xml  { render :xml => @scmail, :status => :created, :location => @scmail }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @scmail.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /scmails/1
  # PUT /scmails/1.xml
  def update
    @scmail = Scmail.find(params[:id])

    respond_to do |format|
      if @scmail.update_attributes(params[:scmail])
        format.html { redirect_to(@scmail, :notice => 'Your Scmail was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @scmail.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scmails/1
  # DELETE /scmails/1.xml
  def destroy
    @scmail = Scmail.find(params[:id])
    @scmail.destroy

    respond_to do |format|
      format.html { redirect_to(scmails_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scmails_helper.rb
module ScmailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maildemo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/scmails/_form.html.erb
<%= form_for(@scmail) do |f| %>
  <% if @scmail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scmail.errors.count, "error") %> prohibited this scmail from being saved:</h2>

      <ul>
      <% @scmail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipient %><br />
    <%= f.text_field :recipient %>
  </div>
  <div class="field">
    <%= f.label :sendto %><br />
    <%= f.text_field :sendto %>
  </div>
  <div class="field">
    <%= f.label :tosendat %><br />
    <%= f.text_field :tosendat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scmails/edit.html.erb
<h1>Editing scmail</h1>

<%= render 'form' %>

<%= link_to 'Show', @scmail %> |
<%= link_to 'Back', scmails_path %>

app/views/scmails/index.html.erb
<h1>Listing scmails</h1>

<table>
  <tr>
    <th>Recipient</th>
    <th>Sendto</th>
    <th>Tosendat</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scmails.each do |scmail| %>
  <tr>
    <td><%= scmail.recipient %></td>
    <td><%= scmail.sendto %></td>
    <td><%= scmail.tosendat %></td>
    <td><%= link_to 'Show', scmail %></td>
    <td><%= link_to 'Edit', edit_scmail_path(scmail) %></td>
    <td><%= link_to 'Destroy', scmail, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scmail', new_scmail_path %>

app/views/scmails/new.html.erb
<h1>New scmail</h1>

<%= render 'form' %>

<%= link_to 'Back', scmails_path %>

app/views/scmails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Recipient:</b>
  <%= @scmail.recipient %>
</p>

<p>
  <b>Sendto:</b>
  <%= @scmail.sendto %>
</p>

<p>
  <b>Tosendat:</b>
  <%= @scmail.tosendat %>
</p>


<%= link_to 'Edit', edit_scmail_path(@scmail) %> |
<%= link_to 'Back', scmails_path %>